services:
  php:
    image: php:8.0-apache
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    command: >
      bash -c "apt-get update && apt-get install -y libpq-dev libzip-dev zip unzip && 
      docker-php-ext-install mysqli pdo pdo_mysql && 
      a2enmod rewrite && 
      apache2-foreground"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: anonymous_wall
      MYSQL_USER: anon_user
      MYSQL_PASSWORD: anon_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  mysql_data: 